services:

  db:
    container_name: pg-db-ticketera
    image: postgres:16-alpine
    restart: always
    networks:
      - ticketera-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ticketera-network

  admin-frontend:
    container_name: ticketera-admin-frontend
    build:
      context: ../admin-ticketera
      dockerfile: admin.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
    environment:
      - NEXT_PUBLIC_API_URL=/api
    ports:
      - "3000:3000"
    env_file:
      - ../admin-ticketera/.env.prod
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ticketera-network

networks:
  ticketera-network:


volumes:
  postgres_data_ticketera:
