version: '3.7'

services:
  app:
    container_name: node-app-ticketera
    build: .
    restart: always
    networks:
      - ticketera-network
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ticketera
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules

  db:
    container_name: pg-db-ticketera
    image: postgres:16-alpine
    restart: always
    networks:
      - ticketera-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticketera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_ticketera:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticketera"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  ticketera-network:

volumes:
  postgres_data_ticketera: