name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}

    - name: Deploy to VPS
      run: |
        ssh -i ${{ github.workspace }}/../private.key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd /root/server-ticketera
          git pull origin main
          npm install
          npm run db:deploy
          pm2 restart server-ticketera
          pm2 save
        EOF
      shell: bash
